import type { ApplicationFormState } from "./types";

export const emptyFormState: ApplicationFormState = {
  firstName: "",
  middleInitial: "",
  lastName: "",
  extensionName: "",
  emailAddress: "",
  address: "",
  phoneNumber: "",
  civilStatus: "",
  gender: "",
  nationality: "",
  birthday: "",
  age: "",
  churchOrganizationAffiliation: "",
  churchAddress: "",
  regionProvince: "",
  position: "",
  positionOthers: "",
  height: "",
  weight: "",
  bloodType: "",
  colorOfEyes: "",
  colorOfSkin: "",
  sssNumber: "",
  tinNumber: "",
  emergencyName: "",
  emergencyCellphone: "",
  elementarySchool: "",
  secondarySchool: "",
  tertiarySchool: [""],
  postGraduateStudies: [""],
  ministerialWorkExperience: [{ rolePosition: "", institution: "", years: "" }],
  skillsTalents: "",
  branchOfService: [],
  branchOfServiceOthers: "",
  characterReferences: [
    { name: "", position: "", contactNumber: "" },
    { name: "", position: "", contactNumber: "" },
    { name: "", position: "", contactNumber: "" },
  ],
  photoUrl: "",
  signatureUrl: "",
  declarationTruthConfirmed: false,
  monthlyPledgeConfirmed: false,
};
