import type { OfficeDirectoryPageData, OfficePerson } from "./office-directory-page";

const ministryServices: OfficePerson[] = [
  { name: "Dr. Lelanie D. Perido", role: "School Chaplaincy / Education" },
  { name: "Rev. Romel L. Abaca", role: "Training and Seminars / Training & Development" },
  { name: "Dr. Emer Jason R. Grepo", role: "Community Development" },
  { name: "To be announced", role: "Follow Up Visitation" },
  { name: "To be announced", role: "Ordination" },
  { name: "To be announced", role: "Devotion & Bible Study" },
  { name: "To be announced", role: "Pastoral Care" },
  { name: "To be announced", role: "Solemnize Marriage" },
  { name: "To be announced", role: "Pastoral Counseling" },
  { name: "To be announced", role: "Spiritual Enhancement" },
  { name: "To be announced", role: "Moral Values & Spiritual Upliftment" },
  { name: "To be announced", role: "House / Company Blessing" },
];

const administration: OfficePerson[] = [
  { name: "To be announced", role: "Human Resource" },
  { name: "To be announced", role: "Information Technology" },
  { name: "To be announced", role: "Accounting" },
  { name: "To be announced", role: "Logistic" },
  { name: "To be announced", role: "Maintenance" },
];

const nationalDirector: OfficePerson[] = [
  { name: "Dr. Lelanie D. Perido", role: "National Chaplain Director, Education" },
  { name: "Dr. Bobby M. Brimon", role: "National Chaplain Director, Humanitarian" },
  { name: "Dr. Analyn M. Tibio", role: "National Chaplain Director, Political Affairs" },
  { name: "Dr. Romel L. Abaca", role: "National Chaplain Director, Training & Development" },
  { name: "Dr. Lelanie C. Junio", role: "National Chaplain Director, Membership & Recruitment" },
  { name: "Bsp. Dr. Ronaldo P. Manalo", role: "National Chaplain Director, Operation" },
  { name: "Rev. Henry S. Bertumen", role: "National Chaplain Director, Security Group / NCR" },
  { name: "Dr. Emer Jason R. Grepo", role: "National Chaplain Director, Community Development" },
  { name: "Rev. Lauro S. Lamento Jr.", role: "National Chaplain Director, Senate" },
  { name: "Rev. Abner P. Tuballes", role: "National Chaplain Director, NAPOLCOM" },
  { name: "Rev. Rhenald L. Lagrimas", role: "National Chaplain Director, Sports", image: "/officers/Lagrimas.jpg" },
  { name: "Rev. Jun Rosello D. Pongco", role: "National Chaplain Director, Hospital", image: "/officers/Pongco.jpg" },
  { name: "Rev. Jonathan I. Balintay", role: "Regional Chaplain Director, Region 1" },
  { name: "Rev. Nestor R. Tangunan", role: "Regional Chaplain Director, Region II" },
  { name: "Rev. Dr. Miller B. Tadeo", role: "Regional Chaplain Director, Region III" },
  { name: "Rev. Conrado C. Perez", role: "Regional Chaplain Director, Region IV A" },
  { name: "Bsp. Fortunato N. Almasco Jr.", role: "Regional Chaplain Director, Region IV B" },
  { name: "Rev. John Rey T. Vallejera", role: "Regional Chaplain Director, Region 6" },
  { name: "Bsp. BethelJames C. Mascardo", role: "Regional Chaplain Director, Negros Oriental" },
  { name: "Chap. Faulkner Faith C. Mascardo", role: "Regional Chaplain Director, Negros Occidental" },
  { name: "Rev. Emilio R. Biag", role: "Regional Deputy Chaplain Director, NCR" },
  { name: "Chap Virlyn C. Balintay", role: "Regional Deputy Chaplain Director, Region 1" },
  { name: "Rev. Rubenson C. Tandoy", role: "Regional Deputy Chaplain Director, Region 3" },
  { name: "Rev. Armando E. Junio", role: "Provincial Chaplain Director, Isabela" },
  { name: "Rev. Rommey Rodriguez", role: "Provincial Chaplain Director, Nueva Ecija" },
  { name: "Rev. Egmedio B. Equila Jr.", role: "Provincial Chaplain Director, Tarlac" },
  { name: "Rev. Abner P. Tuballes", role: "Provincial Chaplain Director, Rizal" },
  { name: "Rev. Edsel R. Alcantara", role: "Provincial Chaplain Director, Cavite" },
  { name: "Rev. Christopher M. Llego", role: "Provincial Chaplain Director, Batangas" },
  { name: "Bsp. Eleanor L. Bendana", role: "Provincial Chaplain Director, Laguna" },
  { name: "Rev. Teddy S. Martinez", role: "Provincial Chaplain Director, Palawan North" },
  { name: "Rev. Danilo T. Sabico", role: "Provincial Chaplain Director, Palawan South" },
  { name: "Chap Andrew Ramon Tiaga", role: "Provincial Chaplain Director, Romblon", image: "/officers/Tiaga.jpg" },
  { name: "Chap John Manlanat", role: "Provincial Chaplain Director, Cebu" },
  { name: "Rev. Samuel D. Ebuetada", role: "Provincial Chaplain Director, Camiguin" },
  { name: "Rev. Juvanny A. Yap", role: "Provincial Chaplain Director, Davao Oriental" },
  { name: "Chap Jerom D. Amoguis", role: "Provincial Chaplain Director, Agusan Del Sur", image: "/officers/Amoguis.jpg" },
  { name: "Chap Enecito M. Galendez", role: "Provincial Chaplain Director, Agusan Del Norte", image: "/officers/Galendez.jpg" },
  { name: "Rev. Romel G. Manes", role: "Provincial Chaplain Director, Mindoro" },
  { name: "Rev. Dr. Sonny T. San Pedro", role: "Provincial Chaplain Director, Bulacan" },
  { name: "Rev. Dr. Hilario C. Gonzales Jr.", role: "Provincial Chaplain Director, Aurora" },
  { name: "Rev. Roger D. Salvador", role: "Provincial Chaplain Director, Ilocos Norte" },
  { name: "Rev. Willie O. Tolentino", role: "Provincial Chaplain Director, Pampanga" },
  { name: "Rev. Francis A. Dela paz", role: "Provincial Deputy Chaplain Director, Tarlac" },
  { name: "Rev. Romel Arnel V. Roque", role: "Provincial Deputy Chaplain Director, Cabanatuan" },
  { name: "Rev. Rodrigo C. Torres III", role: "Provincial Deputy Chaplain Director, Bulacan" },
  { name: "Chap Alejandro A. Salamanca", role: "City Chaplain, Trece Martirez Cavite" },
  { name: "Chap Norman S. Endozo", role: "City Chaplain, General Trias Cavite" },
  { name: "Chap George L. Junio", role: "City Chaplain, Dasmarinas Cavite" },
  { name: "Chap Ronald C. Castillo", role: "City Chaplain, Las Pinas" },
  { name: "Rev. Ellery S. Garvida", role: "City Chaplain, Santa Rosa Laguna" },
  { name: "Rev. Edgar I. Amarante", role: "City Chaplain, Cabuyao City, Laguna" },
  { name: "Chap Noel M. Roldan", role: "City Chaplain, San Pedro City, Laguna" },
  { name: "Rev. Nodel M. Manzo", role: "City Chaplain, Paranaque" },
  { name: "Chap Enrique G. Ancheta", role: "City Chaplain, Quezon City" },
  { name: "Chap Leslie D. Cunanan", role: "City Chaplain, Angeles Pampanga" },
  { name: "Rev. Dr. Eller G. Valencia", role: "City Chaplain, San Fernando Pampanga" },
  { name: "Chap Nemesio Q. Bajana", role: "City Chaplain, Tarlac" },
  { name: "Rev. Roberto D. Malana", role: "Municipal Chaplain, Silang Cavite", image: "/officers/Malana.jpg" },
  { name: "Rev. James Wayne P. Tuballes", role: "Municipal Chaplain, Kawit Cavite" },
  { name: "Rev. Godolfredo G. Javier Jr.", role: "Municipal Chaplain, Naic Cavite" },
  { name: "Rev. Chelito O. Consegra", role: "Municipal Chaplain, Alfonso Cavite" },
  { name: "Rev. Rodrigo S. Fontanilla Jr.", role: "Municipal Chaplain, Gerona Tarlac" },
  { name: "Chap Jessie D. Buniag", role: "Municipal Chaplain, Conception Tarlac" },
  { name: "Chap Alfredo G. Casco", role: "Municipal Chaplain, Santiago Isabela" },
  { name: "Chap Menard Aries Q. Narvas", role: "Municipal Chaplain, Labrador Pangasinan" },
  { name: "Rev. Elmer C. Victoria", role: "Municipal Chaplain, Capas" },
  { name: "Rev. Jessie D. Buniag", role: "Municipal Chaplain, Concepcion" },
  { name: "Rev. Rodrigo S. Fontanilla Jr.", role: "Municipal Chaplain, Gerona" },
  { name: "Rev. Dr June T. Viuya", role: "Municipal Chaplain, La Paz" },
  { name: "Rev. Zosimo Valdez Jr.", role: "Municipal Chaplain, Victoria" },
  { name: "Rev. Rodel E. Banaga", role: "Municipal Chaplain, Sta Ignacia" },
  { name: "Rev. Rionel Eugenio", role: "Municipal Chaplain, Camiling" },
  { name: "Rev. Analiza T. Concepcion", role: "Municipal Chaplain, San Jose" },
  { name: "Rev. Joel Gamasa", role: "Municipal Chaplain, Moncada" },
  { name: "Chap Erviejon A. Labador", role: "Municipal Chaplain, Camiguin" },
  { name: "Chap Francisco P. Pedregoza", role: "Municipal Chaplain, Narra Palawan" },
  { name: "Chap Rodrigo A. Laviano", role: "Municipal Chaplain, Quezon Palawan" },
  { name: "Chap Ramon S. Banes", role: "Municipal Chaplain, Roxas Palawan" },
  { name: "Chap Eliezer M. Gomez", role: "Municipal Chaplain, Dumaran Palawan" },
  { name: "Chap Jemelet M. Reyes", role: "Municipal Chaplain, Angono, Rizal" },
  { name: "Chap John R. Santos", role: "City / Municipal Deputy Chaplain, NCR" },
  { name: "Chap Lorna E. Senting", role: "City / Municipal Deputy Chaplain, Makati" },
  { name: "Rev. Jondie M. Buhat", role: "City / Municipal Deputy Chaplain, Muntinlupa City", image: "/officers/Buhat.jpg" },
  { name: "Rev. Myrie E. Ramila", role: "City / Municipal Deputy Chaplain, San Jose" },
  { name: "Rev. Rico L. Razon", role: "City / Municipal Deputy Chaplain, La Paz" },
  { name: "Rev. Marlo V. Dela Cruz", role: "City / Municipal Deputy Chaplain, Victoria" },
  { name: "Rev. Romuel D. Pimentel", role: "City / Municipal Deputy Chaplain, Capas" },
  { name: "Rev. Rowena I. Gabriel", role: "City / Municipal Deputy Chaplain, Sta Ignacia" },
  { name: "Chap Ramil R. Libarra", role: "City / Municipal Deputy Chaplain, Taguig" },
  { name: "Chap Rose Marie R. Reyes", role: "City / Municipal Deputy Chaplain, Angono, Rizal" },
  { name: "Rev. Roberto G. Parcasio", role: "Northern District Chaplain Director" },
];

const churchesMinisterial: OfficePerson[] = [
  { name: "Dr. Lelanie D. Perido", role: "Education" },
  { name: "Dr. Bobby M. Brimon", role: "Humanitarian" },
  { name: "Dr. Analyn M. Tibio", role: "Political Affairs & Communication" },
  { name: "Dr. Romel L. Abaca", role: "Training & Development" },
  { name: "To be announced", role: "Social Welfare & Development" },
  { name: "To be announced", role: "Human Resources" },
  { name: "Dr. Lelanie C. Junio", role: "Membership & Recruitment" },
  { name: "To be announced", role: "Prison Ministry" },
  { name: "To be announced", role: "School / Colleges" },
  { name: "Rev. Henry S. Bertumen", role: "Security Group" },
  { name: "To be announced", role: "PNP" },
  { name: "Rev. Rhenald L. Lagrimas", role: "Sport" },
];

const partnersNgo: OfficePerson[] = [
  { name: "WCEA", role: "Partner Organization" },
  { name: "JSL Group of Company", role: "Partner Organization" },
  { name: "AYAAN Enterprises Corporation", role: "Partner Organization" },
  { name: "L.A.A Health Talk with Dr. Larry", role: "Partner Organization" },
  { name: "Natural Bone Restoration", role: "Partner Organization" },
];

export const officeDirectoryPages: Record<string, OfficeDirectoryPageData> = {
  "office-ministry-services": {
    title: "Office of the Ministry/Services",
    description:
      "Ministry and Services offices coordinate spiritual care, training, pastoral support, and values-based service programs.",
    people: ministryServices,
  },
  "office-administration": {
    title: "Office of the Administration",
    description:
      "Administration offices support personnel, systems, records, logistics, finance, and maintenance needs of the organization.",
    people: administration,
  },
  "office-national-director": {
    title: "Office of the National Director & Deputy Director",
    description:
      "National, regional, provincial, city, municipal, and deputy chaplain leaders coordinate field operations and local chaplaincy work.",
    people: nationalDirector,
  },
  "office-churches-ministerial": {
    title: "Office of the Churches/Ministerial",
    description:
      "Churches and Ministerial offices handle education, humanitarian work, recruitment, security, and other ministry assignments.",
    people: churchesMinisterial,
  },
  "office-partners-ngo": {
    title: "Office of the Partners-NGO",
    description:
      "Partners and NGO offices list partner organizations connected with programs, outreach, and support activities.",
    people: partnersNgo,
  },
};
