import type { OfficeDirectoryPageData, OfficePerson } from "./office-directory-page";

const ministryServices: OfficePerson[] = [
  { name: "Dr. Lelanie D. Perido", role: "School Chaplaincy / Education" },
  { name: "Rev. Romel L. Abaca", role: "Training and Seminars / Training & Development" },
  { name: "Dr. Emer Jason R. Grepo", role: "Community Development" },
  { name: "To be announced", role: "Follow Up Visitation" },
  { name: "To be announced", role: "Ordination" },
  { name: "To be announced", role: "Devotion & Bible Study" },
  { name: "To be announced", role: "Pastoral Care" },
  { name: "To be announced", role: "Solemnize Marriage" },
  { name: "To be announced", role: "Pastoral Counseling" },
  { name: "To be announced", role: "Spiritual Enhancement" },
  { name: "To be announced", role: "Moral Values & Spiritual Upliftment" },
  { name: "To be announced", role: "House / Company Blessing" },
];

const administration: OfficePerson[] = [
  { name: "To be announced", role: "Human Resource" },
  { name: "To be announced", role: "Information Technology" },
  { name: "To be announced", role: "Accounting" },
  { name: "To be announced", role: "Logistic" },
  { name: "To be announced", role: "Maintenance" },
];

const nationalDirector: OfficePerson[] = [
  { name: "Dr. Lelanie D. Perido", role: "National Chaplain Director, Education" },
  { name: "Dr. Bobby M. Brimon", role: "National Chaplain Director, Humanitarian" },
  { name: "Dr. Analyn M. Tibio", role: "National Chaplain Director, Political Affairs" },
  { name: "Dr. Romel L. Abaca", role: "National Chaplain Director, Training & Development" },
  { name: "Dr. Lelanie C. Junio", role: "National Chaplain Director, Membership & Recruitment" },
  { name: "Bsp. Dr. Ronaldo P. Manalo", role: "National Chaplain Director, Operation" },
  { name: "Rev. Henry S. Bertumen", role: "National Chaplain Director, Security Group / NCR" },
  { name: "Dr. Emer Jason R. Grepo", role: "National Chaplain Director, Community Development" },
  { name: "Rev. Lauro S. Lamento Jr.", role: "National Chaplain Director, Senate" },
  { name: "Rev. Abner P. Tuballes", role: "National Chaplain Director, NAPOLCOM" },
  { name: "Rev. Rhenald L. Lagrimas", role: "National Chaplain Director, Sports", image: "/officers/Lagrimas.jpg" },
  { name: "Rev. Jun Rosello D. Pongco", role: "National Chaplain Director, Hospital", image: "/officers/Pongco.jpg" },
  { name: "Rev. Jonathan I. Balintay", role: "Regional Chaplain Director, Region 1" },
  { name: "Rev. Nestor R. Tangunan", role: "Regional Chaplain Director, Region II" },
  { name: "Rev. Dr. Miller B. Tadeo", role: "Regional Chaplain Director, Region III" },
  { name: "Rev. Conrado C. Perez", role: "Regional Chaplain Director, Region IV A" },
  { name: "Bsp. Fortunato N. Almasco Jr.", role: "Regional Chaplain Director, Region IV B" },
  { name: "Rev. John Rey T. Vallejera", role: "Regional Chaplain Director, Region 6" },
  { name: "Bsp. BethelJames C. Mascardo", role: "Regional Chaplain Director, Negros Oriental" },
  { name: "Chap. Faulkner Faith C. Mascardo", role: "Regional Chaplain Director, Negros Occidental" },
  { name: "Rev. Emilio R. Biag", role: "Regional Deputy Chaplain Director, NCR" },
  { name: "Chap Virlyn C. Balintay", role: "Regional Deputy Chaplain Director, Region 1" },
  { name: "Rev. Rubenson C. Tandoy", role: "Regional Deputy Chaplain Director, Region 3" },
  { name: "Rev. Armando E. Junio", role: "Provincial Chaplain Director, Isabela" },
  { name: "Rev. Rommey Rodriguez", role: "Provincial Chaplain Director, Nueva Ecija" },
  { name: "Rev. Egmedio B. Equila Jr.", role: "Provincial Chaplain Director, Tarlac" },
  { name: "Rev. Abner P. Tuballes", role: "Provincial Chaplain Director, Rizal" },
  { name: "Rev. Edsel R. Alcantara", role: "Provincial Chaplain Director, Cavite" },
  { name: "Rev. Christopher M. Llego", role: "Provincial Chaplain Director, Batangas" },
  { name: "Bsp. Eleanor L. Bendana", role: "Provincial Chaplain Director, Laguna" },
  { name: "Rev. Teddy S. Martinez", role: "Provincial Chaplain Director, Palawan North" },
  { name: "Rev. Danilo T. Sabico", role: "Provincial Chaplain Director, Palawan South" },
  { name: "Chap Andrew Ramon Tiaga", role: "Provincial Chaplain Director, Romblon", image: "/officers/Tiaga.jpg" },
  { name: "Chap John Manlanat", role: "Provincial Chaplain Director, Cebu" },
  { name: "Rev. Samuel D. Ebuetada", role: "Provincial Chaplain Director, Camiguin" },
  { name: "Rev. Juvanny A. Yap", role: "Provincial Chaplain Director, Davao Oriental" },
  { name: "Chap Jerom D. Amoguis", role: "Provincial Chaplain Director, Agusan Del Sur", image: "/officers/Amoguis.jpg" },
  { name: "Chap Enecito M. Galendez", role: "Provincial Chaplain Director, Agusan Del Norte", image: "/officers/Galendez.jpg" },
  { name: "Rev. Romel G. Manes", role: "Provincial Chaplain Director, Mindoro" },
  { name: "Rev. Dr. Sonny T. San Pedro", role: "Provincial Chaplain Director, Bulacan" },
  { name: "Rev. Dr. Hilario C. Gonzales Jr.", role: "Provincial Chaplain Director, Aurora" },
  { name: "Rev. Roger D. Salvador", role: "Provincial Chaplain Director, Ilocos Norte" },
  { name: "Rev. Willie O. Tolentino", role: "Provincial Chaplain Director, Pampanga" },
  { name: "Rev. Francis A. Dela paz", role: "Provincial Deputy Chaplain Director, Tarlac" },
  { name: "Rev. Romel Arnel V. Roque", role: "Provincial Deputy Chaplain Director, Cabanatuan" },
  { name: "Rev. Rodrigo C. Torres III", role: "Provincial Deputy Chaplain Director, Bulacan" },
  { name: "Chap Alejandro A. Salamanca", role: "City Chaplain, Trece Martirez Cavite" },
  { name: "Chap Norman S. Endozo", role: "City Chaplain, General Trias Cavite" },
  { name: "Chap George L. Junio", role: "City Chaplain, Dasmarinas Cavite" },
  { name: "Chap Ronald C. Castillo", role: "City Chaplain, Las Pinas" },
  { name: "Rev. Ellery S. Garvida", role: "City Chaplain, Santa Rosa Laguna" },
  { name: "Rev. Edgar I. Amarante", role: "City Chaplain, Cabuyao City, Laguna" },
  { name: "Chap Noel M. Roldan", role: "City Chaplain, San Pedro City, Laguna" },
  { name: "Rev. Nodel M. Manzo", role: "City Chaplain, Paranaque" },
  { name: "Chap Enrique G. Ancheta", role: "City Chaplain, Quezon City" },
  { name: "Chap Leslie D. Cunanan", role: "City Chaplain, Angeles Pampanga" },
  { name: "Rev. Dr. Eller G. Valencia", role: "City Chaplain, San Fernando Pampanga" },
  { name: "Chap Nemesio Q. Bajana", role: "City Chaplain, Tarlac" },
  { name: "Rev. Roberto D. Malana", role: "Municipal Chaplain, Silang Cavite", image: "/officers/Malana.jpg" },
  { name: "Rev. James Wayne P. Tuballes", role: "Municipal Chaplain, Kawit Cavite" },
  { name: "Rev. Godolfredo G. Javier Jr.", role: "Municipal Chaplain, Naic Cavite" },
  { name: "Rev. Chelito O. Consegra", role: "Municipal Chaplain, Alfonso Cavite" },
  { name: "Rev. Rodrigo S. Fontanilla Jr.", role: "Municipal Chaplain, Gerona Tarlac" },
  { name: "Chap Jessie D. Buniag", role: "Municipal Chaplain, Conception Tarlac" },
  { name: "Chap Alfredo G. Casco", role: "Municipal Chaplain, Santiago Isabela" },
  { name: "Chap Menard Aries Q. Narvas", role: "Municipal Chaplain, Labrador Pangasinan" },
  { name: "Rev. Elmer C. Victoria", role: "Municipal Chaplain, Capas" },
  { name: "Rev. Jessie D. Buniag", role: "Municipal Chaplain, Concepcion" },
  { name: "Rev. Rodrigo S. Fontanilla Jr.", role: "Municipal Chaplain, Gerona" },
  { name: "Rev. Dr June T. Viuya", role: "Municipal Chaplain, La Paz" },
  { name: "Rev. Zosimo Valdez Jr.", role: "Municipal Chaplain, Victoria" },
  { name: "Rev. Rodel E. Banaga", role: "Municipal Chaplain, Sta Ignacia" },
  { name: "Rev. Rionel Eugenio", role: "Municipal Chaplain, Camiling" },
  { name: "Rev. Analiza T. Concepcion", role: "Municipal Chaplain, San Jose" },
  { name: "Rev. Joel Gamasa", role: "Municipal Chaplain, Moncada" },
  { name: "Chap Erviejon A. Labador", role: "Municipal Chaplain, Camiguin" },
  { name: "Chap Francisco P. Pedregoza", role: "Municipal Chaplain, Narra Palawan" },
  { name: "Chap Rodrigo A. Laviano", role: "Municipal Chaplain, Quezon Palawan" },
  { name: "Chap Ramon S. Banes", role: "Municipal Chaplain, Roxas Palawan" },
  { name: "Chap Eliezer M. Gomez", role: "Municipal Chaplain, Dumaran Palawan" },
  { name: "Chap Jemelet M. Reyes", role: "Municipal Chaplain, Angono, Rizal" },
  { name: "Chap John R. Santos", role: "City / Municipal Deputy Chaplain, NCR" },
  { name: "Chap Lorna E. Senting", role: "City / Municipal Deputy Chaplain, Makati" },
  { name: "Rev. Jondie M. Buhat", role: "City / Municipal Deputy Chaplain, Muntinlupa City", image: "/officers/Buhat.jpg" },
  { name: "Rev. Myrie E. Ramila", role: "City / Municipal Deputy Chaplain, San Jose" },
  { name: "Rev. Rico L. Razon", role: "City / Municipal Deputy Chaplain, La Paz" },
  { name: "Rev. Marlo V. Dela Cruz", role: "City / Municipal Deputy Chaplain, Victoria" },
  { name: "Rev. Romuel D. Pimentel", role: "City / Municipal Deputy Chaplain, Capas" },
  { name: "Rev. Rowena I. Gabriel", role: "City / Municipal Deputy Chaplain, Sta Ignacia" },
  { name: "Chap Ramil R. Libarra", role: "City / Municipal Deputy Chaplain, Taguig" },
  { name: "Chap Rose Marie R. Reyes", role: "City / Municipal Deputy Chaplain, Angono, Rizal" },
  { name: "Rev. Roberto G. Parcasio", role: "Northern District Chaplain Director" },
];

const churchesMinisterial: OfficePerson[] = [
  { name: "Dr. Lelanie D. Perido", role: "Education" },
  { name: "Dr. Bobby M. Brimon", role: "Humanitarian" },
  { name: "Dr. Analyn M. Tibio", role: "Political Affairs & Communication" },
  { name: "Dr. Romel L. Abaca", role: "Training & Development" },
  { name: "To be announced", role: "Social Welfare & Development" },
  { name: "To be announced", role: "Human Resources" },
  { name: "Dr. Lelanie C. Junio", role: "Membership & Recruitment" },
  { name: "To be announced", role: "Prison Ministry" },
  { name: "To be announced", role: "School / Colleges" },
  { name: "Rev. Henry S. Bertumen", role: "Security Group" },
  { name: "To be announced", role: "PNP" },
  { name: "Rev. Rhenald L. Lagrimas", role: "Sport" },
];

const createPartnerEntry = (
  name: string,
  category: string,
  image?: string,
): OfficePerson => ({
  name,
  role: category,
  group: category,
  image,
  imageType: "logo",
});

const partnersNgo: OfficePerson[] = [
   createPartnerEntry(
    "JSL Security Group",
    "Chaplain Partner (NGO)",
    "/partners/Chaplain Partner (NGO)/JSL Security Group.jpg",
  ),
  createPartnerEntry(
    "Securities & Exchange Commission",
    "National Accreditations",
    "/partners/National Accreditations/Securities and Exchange Commission.png",
  ),
  createPartnerEntry(
    "Philippine National Police Chaplain Services",
    "National Accreditations",
    "/partners/National Accreditations/Philippine National Police-Chaplain Service.png",
  ),
  createPartnerEntry(
    "Department of the Interior and Local Government",
    "National Accreditations",
    "/partners/National Accreditations/Department of the Interior and Local Government (DILG).png",
  ),
  createPartnerEntry(
    "Recognized by PSA-CRASM",
    "National Accreditations",
    "/partners/National Accreditations/Recognized by PSA-CRASM.jpg",
  ),
  createPartnerEntry(
    "Bureau of Jail Management and Penology",
    "Regional Accreditations",
    "/partners/Regional Accreditations/Bureau of Jail Management and Penology (BJMP).png",
  ),
  createPartnerEntry(
    "DSWD Calabarzon",
    "Regional Accreditations",
    "/partners/Regional Accreditations/Department of Social Welfare and Development(Calabarzon).jpg",
  ),
  createPartnerEntry(
    "DSWD Region 3",
    "Regional Accreditations",
    "/partners/Regional Accreditations/Department of Social Welfare and Development(Region 3).png",
  ),
  createPartnerEntry(
    "DILG-MMAC Region 4-A",
    "Regional Accreditations",
    "/partners/Regional Accreditations/DILG-Multi-Sectoral Advisory Committee (MSAC)  (Region 4-A).jpg",
  ),
  createPartnerEntry(
    "DSWD-4Ps Region 4-A",
    "Regional Accreditations",
    "/partners/Regional Accreditations/DSWD-4Ps-Region 4-A.jpg",
  ),
  createPartnerEntry(
    "Schools Division of Ilocos Norte",
    "Provincial Accreditations",
    "/partners/Provincial Accreditation/DepEd-Ilocos Norte Region 1.jpg",
  ),
  createPartnerEntry(
    "DSWD Cavite PAC Provincial Advisory Council",
    "Provincial Accreditations",
    "https://i-grs.dswd.gov.ph/assets/public_grievance_css/bp_logo.png"
  ),
  createPartnerEntry("Province of Pangasinan", "LGU Accreditation", "/partners/Provincial Accreditation/Pangasinan.png",),
  createPartnerEntry("Municipality of Piddig", "LGU Accreditation", "https://ilocosnorte.gov.ph/images/municipalities/logos/piddig.webp"),
  createPartnerEntry("Municipality of San Nicolas", "LGU Accreditation", "https://ilocosnorte.gov.ph/images/municipalities/logos/san-nicolas.webp"),
  createPartnerEntry("Municipality of Pasuquin", "LGU Accreditation", "https://ilocosnorte.gov.ph/images/municipalities/logos/pasuquin.webp"),
  createPartnerEntry("Municipality of Banna", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTdkJeWXRkblZ0dbxSgFGUm5O8vLtA3-GQsQm-Rp4g65EJk7OoG3rti85jz&s=10"),
  createPartnerEntry("Province of Cagayan", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSv2topR1fJRiQ-G2QqLlXex4_xYW5-BSnPloCTuvJn1Q&s=10"),
  createPartnerEntry("Province of Hagonoy Bulacan", "LGU Accreditation", "https://elgu-news-cdn.e.gov.ph/hagonoy-bulacan/uploads/logo.jpg"),
  createPartnerEntry("City of Santa Rosa Laguna", "LGU Accreditation", "https://upload.wikimedia.org/wikipedia/commons/1/12/Seal_of_Santa_Rosa%2C_Laguna.png"),
  createPartnerEntry("City of Imus Cavite", "LGU Accreditation", "https://upload.wikimedia.org/wikipedia/en/thumb/7/74/Ph_seal_Imus.png/250px-Ph_seal_Imus.png?utm_source=en.wikipedia.org&utm_campaign=parser&utm_content=thumbnail"),
  createPartnerEntry("City of Dasmarinas Cavite", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRIm8fhkyWRtusI5u5r9v_uUDQGxHPKnkQ0117eVLbfwQ&s=10"),
  createPartnerEntry("City of General Trias Cavite", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQDrnTF5eq8K54EHP3J1R2QqOglLRE7bxqV1S7MnnhEgQ&s=10"),
  createPartnerEntry("City of Trece Martires Cavite", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSETxL5QBguAjvrT6nhLGfPrAMK4cOogq3q-f-CgeCBFQ&s"),
  createPartnerEntry("Cavite City", "LGU Accreditation", "https://upload.wikimedia.org/wikipedia/commons/3/36/Cavite_City_Seal.png?utm_source=commons.wikimedia.org&utm_campaign=index&utm_content=original"),
  createPartnerEntry("Municipality of Noveleta Cavite", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQIw867wEW2TB12GnY8eQofgXhzzUpDlykdHrFP-Fq3ee1UX_kj6wrOiv-4&s=10"),
  createPartnerEntry("Municipality of Tanza Cavite", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTYHMHB6pEkjS5Vtuq18Ig1xXrvFANsLpndFUDw1oUk7A&s"),
  createPartnerEntry("Municipality of Rosario Cavite", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSZ4jEz9umO129hM7YZIvnIryw0PdQNxR_5BRiXp4nHpOjjHpbvUZFKJIE&s=10"),
  createPartnerEntry("Municipality of GMA Cavite", "LGU Accreditation", "https://lh3.googleusercontent.com/-HcO0AveIi1pTfdpR2qqag0u-c_4215V_GBoRoUzYWfr88Qq1DpH3ey9zhEFlOD6H8mr_k67STSHUXqrHVGnfKhI5A8G1fcbgA"),
  createPartnerEntry("Municipality of Silang Cavite", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSlaZDwHmti0IeRsxL35fJwrkRuUSIQt4hKG3-4YHW9YQQEoJxrLZxjIDw&s=10"),
  createPartnerEntry("Municipality of Tuy Batangas", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIMDzykgZBYEIYWqIE4fgckU6uVOnvzWLDOIpA1GKaCA&s=10"),
  createPartnerEntry("Municipality of Angono Rizal", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRabGj3IQbq_gKcBSZPHnEX09W6w8cIYVnkGkxNaLy7PA&s"),
  createPartnerEntry("Municipality of Narra Palawan", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVTqxnTT-lHJ8dBdI8YSkZhif3FQVcHkZRxvxSUR_57uR9GKfBb0fYjxg&s=10"),
  createPartnerEntry("Municipality of Dumaran Palawan", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTGMuLyjYrBJ5_Pf0hpUcIEAxQTotvoJO5Wuzm5_U9gtU5-cN300rkcNGc7&s=10"),
  createPartnerEntry("Municipality of Roxas Palawan", "LGU Accreditation", "https://upload.wikimedia.org/wikipedia/commons/4/4f/Flag_of_Roxas%2C_Palawan.png"),
  createPartnerEntry("Municipality of San Isidro", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRW2vyOX5CGUcALImCjPAtjIqAAi4RQWfa5rvS5NOpIgw&s=10"),
  createPartnerEntry("Province of Camiguin", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSEqSFbQv8gHZe6h3YzeacsuiSkmePHUHQxuVesdQBv5Q&s=10"),
  createPartnerEntry("City of Butuan", "LGU Accreditation", "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6PY5TFQyLa0FgFMIG3Uo-JYLC_L15U16pGykerU5Pjw&s=10"),
];

export const officeDirectoryPages: Record<string, OfficeDirectoryPageData> = {
  "office-ministry-services": {
    title: "Office of the Ministry/Services",
    description:
      "Ministry and Services offices coordinate spiritual care, training, pastoral support, and values-based service programs.",
    people: ministryServices,
  },
  "office-administration": {
    title: "Office of the Administration",
    description:
      "Administration offices support personnel, systems, records, logistics, finance, and maintenance needs of the organization.",
    people: administration,
  },
  "office-national-director": {
    title: "Office of the National Director & Deputy Director",
    description:
      "National, regional, provincial, city, municipal, and deputy chaplain leaders coordinate field operations and local chaplaincy work.",
    people: nationalDirector,
  },
  "office-churches-ministerial": {
    title: "Office of the Churches/Ministerial",
    description:
      "Churches and Ministerial offices handle education, humanitarian work, recruitment, security, and other ministry assignments.",
    people: churchesMinisterial,
  },
  "office-partners-ngo": {
    title: "Office of the Partners-NGO",
    description:
      "Partners and NGO offices list partner organizations connected with programs, outreach, and support activities.",
    people: partnersNgo,
  },
};
